
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아디다스 클럽 여름 조거팬츠 트레이닝 바지 808','39700',0 ,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아이다스 검빨 수영복','32450',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아디다스 운동 바지 SD5281','26900',0,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아디다스 불꽃 파이어버드 파랑색 후드','22000',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 스냅백 검골 2018버전','44000',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 신구용 트리플화이트','189000',0,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('유아 모자 스트레이트 포인트','14900',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아동 순면 상 하의 세트 신발','113900',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('유아 침대 잠을편안하게 해줘요','311300',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('러블리 블링블링 블라우스','25000',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('실크 블라우스 블랙 레드 네이비','29800',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('언더핏 남성 기모 후드티','19900',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('탑크리클래식 3컬러 결혼식 캐주얼 남자 정장','75000',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('크리탑 겨울용 키즈 코트','38900',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('수진스컴퍼니 자체제작 노마진 아동 장화 유아 레인부츠 남아 여아 신발 슈즈 우비','11900',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('여성 블랙 네이비 벨벳 롱 스커트','16800',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('여성 체크 남방 셔츠 블랙 그레이 레드','13900',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('수진슈 블랙 펌프스 s1998','25000',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('자체제작 수진스컴퍼니 기모 플랫 로퍼','19900',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('[특가]수진네양말 여성용 양털 겨울양말','2440',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('곤홍삭스 남성용 등산화 양말','3500',0,'',0);


--INSERT INTO USER(EMAIL, PASSWORD, NAME, PHONE, ADDRESS) VALUES('test@test.com', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Tom', '1234','aaa');