INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 NSW 클럽 플리스 기모 조거팬츠 트레이닝 바지 804408','39700',0 ,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 골프 모던핏 폴로 티셔츠','32450',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키프로 쿨 컴프레션 반팔 티셔츠 703094','26900',0,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키코리아 정품 레가시 91 골프 캡모자 892651','22000',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 트랙탑 져지 자켓','44000',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 에어맥스97 운동화 트리플화이트','189000',0,'',0);


INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('기모 스마일토끼 아동복 세트 MNB0388','14900',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('기모 헤이즐 아동복 세트 MNB0395','13900',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아동공용 세이지 슬립색','11300',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('러블리 블링블링 블라우스','25000',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('실크 블라우스 블랙 레드 네이비','29800',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('언더핏 남성 기모 후드티','19900',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('탑크리클래식 3컬러 결혼식 캐주얼 남자 정장','75000',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('크리탑 겨울용 키즈 코트','38900',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('수진스컴퍼니 자체제작 노마진 아동 장화 유아 레인부츠 남아 여아 신발 슈즈 우비','11900',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('여성 블랙 네이비 벨벳 롱 스커트','16800',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('여성 체크 남방 셔츠 블랙 그레이 레드','13900',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('수진슈 블랙 펌프스 s1998','25000',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('자체제작 수진스컴퍼니 기모 플랫 로퍼','19900',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('[특가]수진네양말 여성용 양털 겨울양말','2440',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('곤홍삭스 남성용 등산화 양말','3500',0,'',0);


--INSERT INTO USER(EMAIL, PASSWORD, NAME, PHONE, ADDRESS) VALUES('test@test.com', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Tom', '1234','aaa');