INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아디다스 클럽 여름 조거팬츠 트레이닝 바지 808','39700','ho1.jpg',0 ,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아이다스 검/빨 수영복','32450','ho2.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아디다스 운동 바지 SD5281','26900','ho1.jpg',0,'',0);

INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아디다스 불꽃 파이어버드 파랑색 후드','22000','ho2.jpg',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 스냅백 검/골 2018버전','44000','ho1.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('나이키 신구용 트리플화이트 ','189000','ho2.jpg',0,'',0);


INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('기모 스마일토끼 아동복 세트 MNB0388','14900','ho2.jpg',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('기모 헤이즐 아동복 세트 MNB0395','13900','ho2.jpg',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아동공용 세이지 슬립색','11300','ho2.jpg',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('CE 레이스세트블라우스(0325H809) 빅사이즈 여성의류 미시옷 블라우스','33400','ho2.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('포플러 샤인다이아 니트 원피스 9708 여성 겨울 루즈핏 터틀넥','29800','ho2.jpg',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('통큰마켓 안녕토비 기모 후드티','9900','ho1.jpg',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('아도르클래식 핏좋은 7컬러 결혼식 캐주얼 남자 정장 수트','92000','ho1.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('라우드 여성용 노엘 코트','38900','ho2.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('페이퍼플레인키즈 PK7761 아동 장화 유아 레인부츠 남아 여아 신발 슈즈 우비','21900','ho2.jpg',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('여성 포켓 체크 플레어 A라인 롱 스커트','16800','ho2.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('여성 체키 체크 남방 셔츠','13900','ho1.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('슈즈앤 메리제인 여성 펌프스 sn333','12800','ho2.jpg',2500,'',0);

INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('화려한외출 여성 겨울 2018 기모 퍼 캐주얼 방한화 플랫 로퍼','10600','ho2.jpg',0,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('언니네양말 여성용 겨울양말 앙고라 심플무지','2440','ho2.jpg',2500,'',0);
INSERT INTO PRODUCT(NAME, PRICE, IMAGE, DELIVERY_CHARGE, SIZE, HITCOUNT) VALUES ('유어삭스 남성용 골지무지맨 긴목양말','1200','ho1.jpg',2500,'',0);


--INSERT INTO USER(EMAIL, PASSWORD, NAME, PHONE, ADDRESS) VALUES('test@test.com', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Tom', '1234','aaa');