DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(500) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(100)
);


DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
	ID BIGINT IDENTITY NOT NULL  PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PRICE BIGINT NOT NULL,
	IMAGE VARCHAR(20) NOT NULL,
	DETAIL VARCHAR(100),
	DELIVERY_CHARGE VARCHAR(100) NOT NULL,
	HITCOUNT BIGINT DEFAULT 0,
	SIZE VARCHAR(10),
	COLOR VARCHAR(20),
--	SELLER VARCHAR(100) DEFAULT 'NONAME'
);