DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(500) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(100)
);