DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CART;

CREATE TABLE USER (
	EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(500) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(100)
);

CREATE TABLE CART (
	EMAIL VARCHAR(100) NOT NULL,
	ID BIGINT NOT NULL,
	SIZE VARCHAR(100) NOT NULL,
	COLOR VARCHAR(20) NOT NULL,
	COUNT BIGINT(100),
	PRIMARY KEY(EMAIL, ID, COLOR, SIZE)
);

CREATE TABLE PRODUCT (
--	ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PRICE BIGINT NOT NULL,
	IMAGE VARCHAR(20) NOT NULL,
	DETAIL VARCHAR(100),
	DELIVERY_CHARGE VARCHAR(100) NOT NULL,
	HITCOUNT BIGINT DEFAULT 0,
	SIZE VARCHAR(10),
	COLOR VARCHAR(20)
);

